name: skydash_financial_tracker
description: "A new Flutter project."
publish_to: 'none' 
version: 1.5.0+20

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  jwt_decode: ^0.3.1
  local_auth: ^2.2.0
  package_info_plus: ^8.0.0
  ota_update: ^7.0.2
  url_launcher: ^6.3.1
  pub_semver: ^2.1.4
  logger: ^2.0.0
  another_flushbar: ^1.12.30
  confetti: ^0.7.0
  flutter_markdown: ^0.7.1
  animated_bottom_navigation_bar: ^1.3.3
  flutter_animate: ^4.5.0
  rrule: ^0.2.17
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  open_filex: ^4.7.0
  pdf: ^3.11.0
  printing: ^5.12.0
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  change_app_package_name: ^1.1.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

